### ISSUE TITLE
404 On Read Me Text

### ISSUE THREAD

**Issue by hbarnard** [alecmuffett/they-search-for-you#1]
Thanks for this, v. small issue [They Search For You](https://github.com/alecmuffett/they-search-for-you/blob/main) 404s.

**Comment by alecmuffett** [comment]
Cool! Thanks for the report. Where is the link which this is referenced
from, please?

**Comment by hbarnard** [comment]
It's in the Readme,

**Comment by alecmuffett** [comment]
Could you perhaps share what the surrounding words are / link text is, please?

**Comment by alecmuffett** [comment]
Ah, found it, thanks!
